### ISSUE TITLE
This issue probably needs just an answer...

### ISSUE THREAD

**Issue by drawkula** [wendlers/mpfshell#10]
```
$ ./mpfshell 

** Micropython File Shell v0.7.3, sw@kaltpost.de ** 
-- Running on Python 2.7 using PySerial 3.1 --

mpfs [/]> open ws:lolin-v3-3
webrepl passwd: 
Connected to esp8266
mpfs [/]> exit
No handlers could be found for logger "root"
$ _
```
Is that something to take care of?

```
$ ./mpfshell 

** Micropython File Shell v0.7.3, sw@kaltpost.de ** 
-- Running on Python 2.7 using PySerial 3.1 --

mpfs [/]> open ws:lolin-v3-3
webrepl passwd: 
Connected to esp8266
mpfs [/]> close
mpfs [/]> exit
$ _
```
`close` before `exit` does not yield that message.

**Comment by wendlers** [comment]
Hi,

yes, I see that too every now and then. It comes from the websocket-client module which is not happy that I didn't register a python logger. 

The websocket-client is outputting that comment whenever it got an answer from the ESP on closing with which it is not a 100% happy. When I enable tracing for that module then it outputs everything it has to say on console. And sometimes on exiting, it receives a state which it doesn't like (but I don't care since we exit the program anyways).

I think I will go and add a logger (even so it might not log anything), to get rid of that message.
