### ISSUE TITLE
Automatic serial port selection

### ISSUE THREAD

**Issue by iBobik** [wendlers/mpfshell#82]
esptool can automatically select port:
```
esptool.py v2.5.0
Found 8 serial ports
Serial port /dev/cu.usbserial
```

Could mpfshell do the same if no port was selected?

**Comment by skorokithakis** [comment]
I imagine it could, but we'd need a dependency on esptool, since it uses its own code to detect the port that has an ESP chip connected. I didn't look very deeply into it, so maybe it would be simple to extract that part of the code and just use it.

It would all depend on how much code that would be, as I don't really want to add esptool as a dependency just for detection.
